<?php
// $Id: xoops_version.php,v1.00 2012/01/21 02:32:00 yoshis Exp $
//  ------------------------------------------------------------------------ //
//                        FormMakeX for XOOPS Cube                           //
//                   Copyright (c) 2005 - 2012 Bluemoon inc.                 //
//                       <http://www.bluemooninc.jp/>                        //
//              Original source by : phpESP V1.6.1 James Flemer              //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;
$mydirname = basename( dirname( __FILE__ ) ) ;
if( ! preg_match( '/^(\D+)(\d*)$/' , $mydirname , $regs ) ) echo ( "invalid dirname: " . htmlspecialchars( $mydirname ) ) ;
$mydirnumber = $regs[2] === '' ? '' : intval( $regs[2] ) ;
/**
 * Setup globals for later use
 */
Global $xoopsDB, $xoopsUser, $xoopsModule;
Global $xoopsModuleConfig;

$modversion['name'] = _MI_BMSURVEY_NAME . $mydirnumber ;
$modversion['version'] = 1.00;
$modversion['description'] = _MI_BMSURVEY_DESC;
$modversion['author'] = "Yoshi Sakai";
$modversion['credits'] = "Copright(c) Bluemoon inc. "
."Based By phpESP project";
$modversion['help'] = "bmsurvey.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/bmsurvey_slogo.png";
$modversion['dirname'] = $mydirname;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "bmsurvey_realm";
$modversion['tables'][1] = "bmsurvey_respondent";
$modversion['tables'][2] = "bmsurvey_designer";
$modversion['tables'][3] = "bmsurvey_form" ;
$modversion['tables'][4] = "bmsurvey_question_type" ;
$modversion['tables'][5] = "bmsurvey_question" ;
$modversion['tables'][6] = "bmsurvey_question_choice" ;
$modversion['tables'][7] = "bmsurvey_access" ;
$modversion['tables'][8] = "bmsurvey_response" ;
$modversion['tables'][9] = "bmsurvey_response_bool" ;
$modversion['tables'][10] = "bmsurvey_response_single" ;
$modversion['tables'][11] = "bmsurvey_response_multiple" ;
$modversion['tables'][12] = "bmsurvey_response_rank" ;
$modversion['tables'][13] = "bmsurvey_response_text" ;
$modversion['tables'][14] = "bmsurvey_response_other" ;
$modversion['tables'][15] = "bmsurvey_response_date" ;


// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";	//manage.php";
$modversion['adminmenu'] = "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][] = array('file' => 'bmsurvey_list.html'	,		'description' => 'List of Form');
$modversion['templates'][] = array('file' => 'bmsurvey_index.html'	,		'description' => 'index');
$modversion['templates'][] = array('file' => 'bmsurvey_controlpanel.html',	'description' => 'Control Panel');
$modversion['templates'][] = array('file' => 'bmsurvey_form.html',		'description' => 'Form Render');
$modversion['templates'][] = array('file' => 'bmsurvey_form_forms.html',	'description' => 'Form Form');
$modversion['templates'][] = array('file' => 'bmsurvey_editform.html',		'description' => 'Form Design');
$modversion['templates'][] = array('file' => 'bmsurvey_manage.html',		'description' => 'Form Manager');
$modversion['templates'][] = array('file' => 'bmsurvey_general.html',		'description' => 'General');
$modversion['templates'][] = array('file' => 'bmsurvey_questions.html',		'description' => 'Questions');
$modversion['templates'][] = array('file' => 'bmsurvey_order.html',			'description' => 'Order');
$modversion['templates'][] = array('file' => 'bmsurvey_preview.html',		'description' => 'Preview');
$modversion['templates'][] = array('file' => 'bmsurvey_webform.html',		'description' => 'Web Form');
$modversion['templates'][] = array('file' => 'bmsurvey_manage_results.html','description' => 'Results view');
$modversion['templates'][] = array('file' => 'bmsurvey_manage_results_chart.html','description' => 'Results view');
$modversion['templates'][] = array('file' => 'bmsurvey_message.html'	,		'description' => 'message');

// Blocks
$modversion['blocks'][1]['file'] = "bmsurvey_top.php";
$modversion['blocks'][1]['name'] = _MI_BMSURVEY_BNAME1.$mydirnumber;
$modversion['blocks'][1]['description'] = "FormMakeX" ;
$modversion['blocks'][1]['show_func'] = "b_bmsurvey_show";
$modversion['blocks'][1]['edit_func'] = "b_bmsurvey_edit";
$modversion['blocks'][1]['template'] = "bmsurvey".$mydirnumber."_block.html";
$modversion['blocks'][1]['can_clone'] = true ;
$modversion['blocks'][1]['options'] = "{$mydirname}|1";

// Comments
$modversion['hasComments'] = 0;

// Admin Preferences
// 2005/05/22 Add by Y.Sakai
$modversion['config'][] = array(
	'name'        => 'CSV_CHARSET',
	'title'       => '_MI_BMSURVEY_CSVCHARSET',
	'description' => '_MI_BMSURVEY_CSVCHARSET_DESC',
	'formtype'    => 'textbox',
	'valuetype'   => 'text',
	'default'     => 'SJIS'
);
$modversion['config'][] = array(
	'name'        => 'CSV_OTHERF',
	'title'       => '_MI_BMSURVEY_CSVOTHERF',
	'description' => '_MI_BMSURVEY_CSVOTHERF_DESC',
	'formtype'    => 'textbox',
	'valuetype'   => 'text',
	'default'     => 'Other(%s)'
);
$modversion['config'][] = array(
	'name'        => 'MANAGERS',
	'title'       => '_MI_BMSURVEY_MANAGEGROUP',
	'description' => '_MI_BMSURVEY_MANAGEGROUP_DESC',
	'formtype'    => 'group_multi',
	'valuetype'   => 'array',
	'default'     => array(1)
);
$modversion['config'][] = array(
	'name'        => 'PSTATUS',
	'title'       => '_MI_BMSURVEY_MGPSTATUS',
	'description' => '_MI_BMSURVEY_MGPSTATUS_DESC',
	'formtype'    => 'yesno',
	'valuetype'   => 'int',
	'default'     => 1
);
$modversion['config'][] = array(
	'name'        => 'BLOCKLIST',
	'title'       => '_MI_BMSURVEY_BLOCKLIST',
	'description' => '_MI_BMSURVEY_BLOCKLIST_DESC',
	'formtype'    => 'textbox',
	'valuetype'   => 'int',
	'default'     => 10
);

$modversion['config'][] = array(
	'name'        => 'ADD_USAGE',
	'title'       => '_MI_BMSURVEY_ADDUSAGE',
	'description' => '_MI_BMSURVEY_ADDUSAGE_DESC',
	'formtype'    => 'yesno',
	'valuetype'   => 'int',
	'default'     => 1
);
$modversion['config'][] = array(
	'name'        => 'ONE_RESPONSE',
	'title'       => '_MI_BMSURVEY_ONERESPONSE',
	'description' => '_MI_BMSURVEY_ONERESPONSE_DESC',
	'formtype'    => 'yesno',
	'valuetype'   => 'int',
	'default'     => 0
);
$modversion['config'][] = array(
	'name'        => 'RESET_RB',
	'title'       => '_MI_BMSURVEY_RESETRADIOBUTTON',
	'description' => '_MI_BMSURVEY_RESETRADIOBUTTON_DESC',
	'formtype'    => 'yesno',
	'valuetype'   => 'int',
	'default'     => 1
);
$modversion['config'][] = array(
	'name'        => 'RESULT_RANK',
	'title'       => '_MI_BMSURVEY_RESULTRANK',
	'description' => '_MI_BMSURVEY_RESULTRANK_DESC',
	'formtype'    => 'select',
	'valuetype'   => 'int',
	'default'     => 0,
	'options'     => array('Avarage' => 0,'Count' => 1)
);
$modversion['config'][] = array(
	'name'        => 'UNSET_GROUP',
	'title'       => '_MI_BMSURVEY_UNSETGROUP',
	'description' => '_MI_BMSURVEY_UNSETGROUP_DESC',
	'formtype'    => 'textbox',
	'valuetype'   => 'text',
	'default'     => null
);
$modversion['config'][] = array(
	'name'        => 'GROBAL_GROUP',
	'title'       => '_MI_BMSURVEY_GROBALGROUP',
	'description' => '_MI_BMSURVEY_GROBALGROUP_DESC',
	'formtype'    => 'textbox',
	'valuetype'   => 'text',
	'default'     => "2|3"
);
$modversion['config'][] = array(
	'name'        => 'INVALID_JUMPURI',
	'title'       => '_MI_BMSURVEY_INVALIDJUMPURI',
	'description' => '_MI_BMSURVEY_INVALIDJUMPURI_DESC',
	'formtype'    => 'textbox',
	'valuetype'   => 'text',
	'default'     => null
);
$modversion['config'][] = array(
	'name'        => 'SUBMIT_JUMPURI',
	'title'       => '_MI_BMSURVEY_SUBMITJUMPURI',
	'description' => '_MI_BMSURVEY_SUBMITJUMPURI_DESC',
	'formtype'    => 'textbox',
	'valuetype'   => 'text',
	'default'     => null
);
$modversion['config'][] = array(
	'name'        => 'SHOW_PUBLIC_TO_OTHERGROUP',
	'title'       => '_MI_SHOW_PUBLIC_TO_OTHERGROUP',
	'description' => '_MI_SHOW_PUBLIC_TO_OTHERGROUP_DESC',
	'formtype'    => 'yesno',
	'valuetype'   => 'int',
	'default'     => 0
);

